gen:
	abigen --sol Token.sol --pkg contracts --out token.go
	abigen --sol TradeToken.sol --pkg contracts --out trade_token.go
	abigen --sol DDContractList.sol --pkg contracts --out ddcontract_list.go
